### ISSUE TITLE
Copyright notice is always stripped

### ISSUE THREAD

**Issue by meleyal** [brunch/uglify-js-brunch#20]
I tried the following, but my copyright notice is always stripped in the minified `app.js`.

In `application.coffee` I tried adding `!` and `@license` to the comment:

```coffeescript
###!
@license app.js
Copyright 2014 blah...
###
```

In `brunch-config.coffee` I tried the following options:

```coffeescript
exports.config:
  plugins:
    uglify:
      comments: 'all'
      preamble: '# hello'
```

**Comment by tudo** [comment]
use as following:
````
plugins:
    uglify:
       output:
           comments: 'all'
````
you can also use a regexp for the comments value ( for example: ```` comments: /@license|@preserve|^!/ ```` ) in order to keep only the comments that contain specific strings

**Comment by es128** [comment]
Thanks @tudo
