### ISSUE TITLE
Fatal error when setting uglify.ignored

### ISSUE THREAD

**Issue by red7adam** [brunch/uglify-js-brunch#21]
I want Uglify to ignore app.js but minify vendor.js and lib.js (app.js will be run through Closure using after-brunch)

However, using config.plugins.uglify.ignored = /app.js/ gives me an error when I do brunch build --production

error checking ignores files to uglify:TypeError: Object {"version":3, "file":"../game/js/app.js", "sources":["app/source1.js", "app/source2.js"], "names":[], "mappings":";;;;;...   ...AACA, "sourcesContent":["....;"]} has no method 'toJSON'

I am using"
uglify-js-brunch v1.7.7 
brunch v1.7.13 (I have in fact also installed brunch using npm install -g brunch/brunch which should be a more up to date version?) 

Relevant bits of config:

exports.config =
  files:
    javascripts:
      joinTo: 
        'js/app.js': /^app/
        'js/lib.js': /^bower_components/
        'js/vendor.js': /^vendor/

plugins:
    uglify:
      mangle: true
      compress: true
      ignored: /app.js/

**Comment by shvaikalesh** [comment]
Closed for inactivity. Please reopen if the issue persists with latest Brunch & plugins.
