### ISSUE TITLE
rename minjs

### ISSUE THREAD

**Issue by stoufdev** [brunch/uglify-js-brunch#26]
Possible to rename the app.js minifyed like app.min.js ?

**Comment by es128** [comment]
Specify in your `joinTo` that you want the target file to be named `app.min.js`. If you want it different depending on minified vs non-minified builds, use [environments and overrides](https://github.com/brunch/brunch/blob/master/docs/config.md#overrides).

**Comment by stoufdev** [comment]
ok ! Possible to force minify in dev mode ?

**Comment by es128** [comment]
Yes, just add `optimize: true` in config

**Comment by stoufdev** [comment]
yes, that was my idea, but not work..where to write it

**Comment by es128** [comment]
top level config object

https://github.com/brunch/brunch/blob/master/docs/config.md#optimize

**Comment by stoufdev** [comment]
ok, but it's for global, not just uglify-js-brunch. Thanks

**Comment by es128** [comment]
To turn on just uglify regardless of optimize setting or production flag you could instead use `plugins: on: ['uglify-js-brunch']`

https://github.com/brunch/brunch/blob/master/docs/config.md#plugins
