### ISSUE TITLE
Supporting uglify-es?

### ISSUE THREAD

**Issue by lunanigra** [brunch/uglify-js-brunch#40]
Hello,

What about supporting ES6, e.g. including uglify-es?

This would help using other libs that require ES6, e.g. @yaga/leaflet-ng2.

Thanks, JC

**Comment by buckle2000** [comment]
Also had a problem here.

This lib cannot process ``string with ${arguments}``

**Comment by tylergould** [comment]
@shvaikalesh any help needed before https://github.com/brunch/uglify-js-brunch/pull/41 can be merged?

**Comment by emeidell** [comment]
Any updates on this?

**Comment by pablohirafuji** [comment]
For anyone who wants to use the updated branch, update your package.json with this:
```
"devDependencies": {
....
    "uglify-js-brunch": "git+ssh://git@github.com:brunch/uglify-js-brunch.git#update-uglifyjs"
....
```
Then `npm install`
