### ISSUE TITLE
Can't generate a production build

### ISSUE THREAD

**Issue by arimourao** [brunch/uglify-js-brunch#42]
I followed the instructions present in the README of this repo, but I still can't generate a production ready build. I get the following warning: _It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details._

Here is my entire webpack.config.js

`
const path = require('path');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
  template: './src/index.html',
  filename: 'index.html',
  inject: 'body'
});

module.exports = {
  entry: './src/index.jsx',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'views/panel')
  },
  plugins: {
    uglify: {
      mangle: false,
      compress: {
        global_defs: {
          DEBUG: false
        }
      }
    }
  },
  module: {
    loaders: [
      { 
        test: /\.jsx?$/, 
        loader: 'babel-loader', 
        exclude: /node_modules/,
      },
      { 
        test: /\.css$/, 
        loader: "style-loader!css-loader"
      }
    ],
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: "babel-loader"
          },
          {
            loader: "eslint-loader",
            options: {
              fix: true
            }
          }
        ]
      },
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      },
      {
        test: /\.(png|woff|woff2|eot|ttf|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader'
      }
    ],
  },
  devtool: 'inline-source-map',
  plugins: [
    HtmlWebpackPluginConfig,
    new UglifyJSPlugin()
  ]
};`

**Comment by paulmillr** [comment]
Why are you mentioning Webpack in a repo for **Brunch**?

**Comment by arimourao** [comment]
How am I supposed to run this brunch then??

**Comment by paulmillr** [comment]
See http://brunch.io for documentation.

You are including *Webpack* config, which is an **entirely different software** and is unrelated to Brunch.

**Comment by beznosd** [comment]
Production build of react app in 3 steps with *Brunch*:
1. Create folder for your new app
`$ mkdir test-app && cd test-app`
2. Use react skeleton to set up new react project. More detail about skeletons [here](http://brunch.io/skeletons).
`$ brunch new -s react`
3. Do a production build of your app
`$ brunch build -p`

If you need to customize your build (change folder structure of the project or add some plugins or ...), you can read the [docs](http://brunch.io/docs/getting-started) for further details.

Enjoy using brunch!
